#!/bin/bash

rm webproxy
ps -ef | grep webproxy | grep -v grep | awk '{print $2}' | xargs kill
echo "Compiling..."
g++ -std=c++11 webproxy.cpp
export http_proxy=127.0.0.1:8001
mv a.out webproxy
./webproxy 8001&
